### ISSUE TITLE
Need Refactoring of Code

### ISSUE THREAD

**Issue by Pratyayee98** [ashutoshbeau/designLab#1]
There should be distinct control and entity class. That shall itself enable Unit Testing.

**Comment by ashutoshbeau** [comment]
Yes, have created different entity classes and have separated the control classes from the boundary classes. So now the unit testing can be done successfully.

**Comment by Pratyayee98** [comment]
Yes, Classes were refactored and 16/16 unit cases passed successfully @ashutoshbeau
