### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Amit9587** [ashutoshbeau/designLab#2]
Session variable for user,volunteer and operator is not getting initialized during login.

**Comment by ashutoshbeau** [comment]
Yes, that's why the table creation was having some less information to display.

**Comment by ashutoshbeau** [comment]
Ok, the password passed during login was not encrypted before passing it to the query, that was the reason behind the issue. So now I've fixed this, you can check it.

**Comment by Amit9587** [comment]
OK, I have verified it and Yes Issue is resolved now.
